SHELL := /bin/sh

q1:
	docker build --help | grep "Write the image ID to the file"

q2:
	sh q2.sh



# docker run -it  \
# 	--network=week-1_default \
# 	taxi_ingest:v001 \
# 		--user=root \
# 		--password=root \
# 		--host=pgdatabase \
# 		--port=5432 \
# 		--db=ny_taxi \
# 		--table_name=yellow_taxi_data \
# 		--url="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz" \


# docker run -it  \
#     --network=week-1_default \
#     taxi_ingest:v002 \
#       --user=root \
#       --password=root \
#       --host=pgdatabase \
#       --port=5432 \
#       --db=ny_taxi \
#       --table_name=yellow_taxi_zone_data \
#       --url="https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv" \
